version: '3.8'

services:
  book_looker_api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    env_file:
      - .env
  
  book_looker_app:
    build:
      context: ./app
    ports:
      - "5123:5123"
    env_file:
      - .env

  celery:
    build:
      context: ./api
    command: celery -A setup worker --loglevel=info
    env_file:
      - .env

  celery_beat:
    build:
      context: ./api
    command: celery -A setup beat --loglevel=info
    env_file:
      - .env