version: '3.8'

services:
  book_looker_api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    env_file:
      - .env

  celery:
    build:
      context: ./api
    command: celery -A setup worker --loglevel=info
    env_file:
      - .env