version: '3.8'

services:
  redis:
      image: redis:latest

  book_looker:
    build:
      context: ./app
    ports:
      - "5123:5123"
    depends_on:
      - database
    env_file:
      - .env

  celery:
    build:
      context: ./app
    command: celery -A setup worker --loglevel=info
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
