version: '3.8'

services:
  redis:
      image: redis:latest
      ports:
        - "6379:6379"

  book_looker:
    build:
      context: ./app
    ports:
      - "5123:5123"
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  redis_data:
